- type: job
  id: SPChemist
  name: job-name-sp-chemist
  description: job-description-sp-chemist
  playTimeTracker: JobSPChemist
  requirements:
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 14400 #4 hrs
  startingGear: SPChemistGear
  icon: "JobIconChemist"
  supervisors: job-supervisors-md
  access:
  - Medical
  - Chemistry
  - Maintenance

- type: startingGear
  id: SPChemistGear
  equipment:
    id: ChemistryPDA
    ears: ClothingHeadsetMedical
    belt: ChemBag
    pocket1: HandLabeler
    eyes: ClothingEyesGlassesChemical
  #storage:
    #back:
    #- Stuff
