- type: job
  id: AtmosphericSpecialist
  name: job-name-atmospec
  description: job-description-atmostech
  playTimeTracker: JobAtmosphericSpecialist
  weight: 10
  requirements:
    - !type:DepartmentTimeRequirement
      department: Maintenance
      time: 54000 # 15 hrs
  startingGear: AtmosphericSpecialistGear
  icon: "JobIconAtmosphericSpecialist"
  supervisors: job-supervisors-hom
  access:
  - Maintenance
  - Engineering
  - External
  - Atmospherics

- type: startingGear
  id: AtmosphericSpecialistGear
  equipment:
    eyes: ClothingEyesGlassesMeson
    id: AtmosPDA
    belt: ClothingBeltUtilityEngineering
    ears: ClothingHeadsetEngineering
  #storage:
    #back:
    #- Stuff
