- type: job
  id: SPQuartermaster
  name: job-name-sp-qm
  description: job-description-sp-qm
  playTimeTracker: JobSPQuartermaster
  requirements:
    - !type:RoleTimeRequirement
      role: JobSPCargoTechnician
      time: 21600 #6 hrs
    - !type:DepartmentTimeRequirement
      department: Cargo
      time: 36000 #10 hours
    - !type:OverallPlaytimeRequirement
      time: 144000 #40 hrs
  weight: 10
  startingGear: SPQuartermasterGear
  icon: "JobIconQuarterMaster"
  supervisors: job-supervisors-warden
  canBeAntag: false
  access:
  - Cargo
  - Salvage
  - Quartermaster
  - Maintenance
  - Command
  - Brig
  - Cryogenics
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff

- type: startingGear
  id: SPQuartermasterGear
  equipment:
    id: QuartermasterPDA
    ears: ClothingHeadsetQM
    belt: BoxFolderClipboard
    pocket1: AppraisalTool
  storage:
    back:
    - Flash
